- name: Install Common Packages
  dnf: 
    name:
      - git
      - jq

- name: Copy Scrypt File
  copy:
    src: "roles/common/files/make_envfile.sh"
    dest: "/home/ec2-user/"
    backup: no
    owner: ec2-user
    group: ec2-user
    mode: 0755