- name: Install Nginx Packages
  yum:
    name: nginx
    state: latest

- name: Start Nginx Service
  systemd: name=nginx enabled=yes state=started

- name: Create directory
  file:
    path: /var/www/menta
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: 0755

- name: Copy Nginx Files
  copy:
    src: "{{item.src}}"
    dest: "/etc/nginx/{{ item.dest }}"
    backup: no
    owner: root
    group: root
  loop:
    - { src: roles/nginx/files/conf.d/menta.devcloudwork.net.conf , dest: conf.d/ }
    - { src: roles/nginx/files/conf.d/log.conf , dest: conf.d/ }
    - { src: roles/nginx/files/nginx.conf, dest: . }
  notify: restart nginx